#!/bin/bash
#
# chkconfig: 35 90 12
# description: VisionDataLoad server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service 
start() {
        initlog -c "echo -n Starting VDL server: "
        /opt/vdl/vdl.py &
        success $"VDL Server Started"
        echo
}
# Restart the service vdl
stop() {
        initlog -c "echo -n Stopping VDL server: "
        killproc vdl.py
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0